### ISSUE TITLE
Rubric and Scores Backend

### ISSUE THREAD

**Issue by rpgroves** [5i-The-Fly/diamond-project04-5i#14]

**Comment by downloadjpg** [comment]
Getting some errors before the docker fully completes

![Image](https://github.com/5i-The-Fly/diamond-project04-5i/assets/53020248/6c11c646-2d2c-4e26-bcca-9363511eb410)

**Comment by cyrus-estavillo** [comment]
Currently working on a test function to console log all of the information we need to pull from the backend.

The following routes/functions need to be implemented:

- [x] getTemplateRubricMaxScore
- [x] getSessionsForStudent
- [x] getSubmissionsForSession
- [x] getScoredRubricForSubmission

Not quite sure how to do this yet but the next step is to rewatch some of David's backend videos and figure it out.

**Comment by cyrus-estavillo** [comment]
Routes implemented. Backend and frontend now connected (albeit a bit roughly). 
High Points:
- [x] The backend is finally connected in some way! Only one bullet point but a pretty big deal and pretty significant for our overall success

What's Next:
- [x] TeacherGradebook.jsx must be refreshed for some reason before the table displays (likely to do with the table rendering in the useEffect function. Figure out why and fix it
- [x] Editing a grade does not yet change the student's score (in the backend) for that submission
   - [x] Need to figure out what 'score' an edit will change. A student essentially needs to have a score for a particular assignment, which is either made up of their best submitted score, or the grade that the teacher manually overrides in the gradebook. Not quite sure how to do it yet. I've done 7 hours of straight programming today so I'm fried. Will think about it tomorrow
- [x] Likely need to refine and test much more extensively

**Comment by cyrus-estavillo** [comment]
Rubric and scores integrated properly. Testing completed.
