### ISSUE TITLE
Post the new server ER Diagram in server ReadMe

### ISSUE THREAD

**Issue by rpgroves** [5i-The-Fly/diamond-project04-5i#16]

**Comment by downloadjpg** [comment]
Consider making it a separate file such as Diamond-5i-Additions.md to avoid merge conflicts with other groups

**Comment by cyrus-estavillo** [comment]
I did make it a different file and simply changed the route in the readMe. However, I still need to put it in the develop branch, not the teacher-gradebook-branch where it currently exists.

**Comment by cyrus-estavillo** [comment]
This can now be found in the develop branch.
