### ISSUE TITLE
Create Dummy Data (See comments)

### ISSUE THREAD

**Issue by rpgroves** [5i-The-Fly/diamond-project04-5i#17]
All dummy data will relate to the "Potions" class.

Subtasks 
- [X] Create template rubric for each activity in the "Fossil Fuels" lesson module
    - [X] Activity Level 1
    - [X] Activity Level 2
    - [X] Activity Level 3
- [X] For each student, create at least one submission attempt for each activity:
    - [X] Colin
        - [X] Activity Level 1
        - [X] Activity Level 2
        - [X] Activity Level 3
     - [X] Ginny
         - [X] Activity Level 1
         - [X] Activity Level 2
         - [X] Activity Level 3
     - [X] Avery
         - [X] Activity Level 1
         - [X] Activity Level 2
         - [X] Activity Level 3
     - [X] David
         - [X] Activity Level 1
         - [X] Activity Level 2
         - [X] Activity Level 3

- [X] For each submission attempt, create a scored rubric instance that references that template rubric for the activity
    - [X] Colin
        - [X] Activity Level 1
        - [X] Activity Level 2
        - [X] Activity Level 3
     - [X] Ginny
        - [X] Activity Level 1
        - [X] Activity Level 2
        - [X] Activity Level 3
     - [X] Avery
         - [X] Activity Level 1
         - [X] Activity Level 2
         - [X] Activity Level 3
     - [X] David
         - [X] Activity Level 1
         - [X] Activity Level 2
         - [X] Activity Level 3

**Comment by rpgroves** [comment]
Create a dummy template rubric for every activity in a class them dummy submissions for every student taking the activity. This is so we can test whether we are properly pulling the data

**Comment by cyrus-estavillo** [comment]
Finished this. Hopefully no bugs, but its all test data. Vinyl should be working to create the true JSON format for the template rubric structure.
